namespace Zeus.LocalApi;

/// <summary>A bounded bitmap generated by ZEUS, without downloaded assets or command execution.</summary>
internal static class WallpaperImage
{
    public static byte[] Create(uint accent, uint background)
    {
        const int width = 960, height = 540;
        const int stride = width * 3;
        using var stream = new MemoryStream(54 + stride * height);
        using var writer = new BinaryWriter(stream);
        writer.Write((ushort)0x4d42); writer.Write(54 + stride * height); writer.Write(0); writer.Write(54);
        writer.Write(40); writer.Write(width); writer.Write(height); writer.Write((ushort)1); writer.Write((ushort)24);
        writer.Write(0); writer.Write(stride * height); writer.Write(2835); writer.Write(2835); writer.Write(0); writer.Write(0);
        var row = new byte[stride];
        for (var y = 0; y < height; y++)
        {
            for (var x = 0; x < width; x++)
            {
                var dx = (x - width * .72) / width;
                var dy = (y - height * .6) / height;
                var strength = Math.Clamp(.55 * Math.Exp(-9 * (dx * dx + dy * dy)), 0, .55);
                for (var channel = 0; channel < 3; channel++)
                {
                    var bg = (background >> (channel * 8)) & 255;
                    var fg = (accent >> (channel * 8)) & 255;
                    row[x * 3 + channel] = (byte)Math.Round(bg + (fg - (double)bg) * strength);
                }
            }
            writer.Write(row);
        }
        writer.Flush();
        return stream.ToArray();
    }
}
