<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Zeus.Windows/Zeus.Windows.csproj" />
    <ProjectReference Include="../Zeus.Core/Zeus.Core.csproj" />
  </ItemGroup>
</Project>
