using System.Diagnostics;
using System.Text;
using Zeus.Core;
using Zeus.Windows;

namespace Zeus.Maintenance;

internal sealed record CommandResult(int ExitCode, string Output, bool TimedOut, string LogFile, string? LogError);

internal static class CommandRunner
{
    internal static async Task<CommandResult> CreateRestorePointAsync(Guid sessionId)
    {
        // The only interpolated text is a GUID generated by the desktop and strictly parsed by the helper.
        var description = "ZEUS " + sessionId.ToString("D");
        var script = "& { $ErrorActionPreference = 'Stop'; try { " +
            "$prior = @(Microsoft.PowerShell.Management\\Get-ComputerRestorePoint -ErrorAction Stop); $before = 0; " +
            "if ($prior.Count -gt 0) { $before = ($prior | Microsoft.PowerShell.Utility\\Measure-Object -Property SequenceNumber -Maximum).Maximum }; " +
            $"$description = '{description}'; " +
            "Microsoft.PowerShell.Management\\Checkpoint-Computer -Description $description -RestorePointType MODIFY_SETTINGS -ErrorAction Stop; " +
            "$created = @(Microsoft.PowerShell.Management\\Get-ComputerRestorePoint -ErrorAction Stop | Microsoft.PowerShell.Core\\Where-Object { $_.Description -eq $description -and $_.SequenceNumber -gt $before }); " +
            "if ($created.Count -ne 1) { throw 'Nenhum novo ponto de restauração foi confirmado.' }; " +
            "Microsoft.PowerShell.Utility\\Write-Output ('ZEUS_RESTORE_POINT_CONFIRMED ' + $created[0].SequenceNumber); exit 0 " +
            "} catch { Microsoft.PowerShell.Utility\\Write-Error $_ -ErrorAction Continue; exit 1 } }";
        return await RunAsync(sessionId, "restore-point.log", TrustedPowerShell.Create(script,
            WindowsPowerShellModule.Management, WindowsPowerShellModule.Utility), TimeSpan.FromMinutes(12));
    }

    internal static async Task<MaintenanceStepResult> ExecuteAsync(Guid sessionId, MaintenanceActionId action)
    {
        ProcessStartInfo start;
        var repair = MaintenanceCatalog.Get(action).RequiresRestorePoint;
        var logName = action + ".log";
        switch (action)
        {
            case MaintenanceActionId.DefenderQuickScan:
                start = TrustedPowerShell.Create(WrapPowerShell(
                    "$status = Defender\\Get-MpComputerStatus -ErrorAction Stop; " +
                    "if (-not $status.AntivirusEnabled -or $status.AMRunningMode -ne 'Normal') { throw 'Defender não está ativo no modo normal. Respeite o antivírus instalado.' }; " +
                    "Defender\\Start-MpScan -ScanType QuickScan -ErrorAction Stop; " +
                    "Defender\\Get-MpComputerStatus | Microsoft.PowerShell.Utility\\Select-Object QuickScanStartTime,QuickScanEndTime,AntivirusEnabled | Microsoft.PowerShell.Utility\\Format-List"),
                    WindowsPowerShellModule.Utility, WindowsPowerShellModule.Defender);
                break;
            case MaintenanceActionId.ScanWindowsImage:
            case MaintenanceActionId.RepairWindowsImage:
                var servicingName = action == MaintenanceActionId.ScanWindowsImage ? "dism-scan-servicing.log" : "dism-repair-servicing.log";
                using (SessionStore.CreateLog(sessionId, servicingName)) { }
                var servicingLog = Path.Combine(SessionStore.GetSessionDirectory(sessionId), servicingName);
                start = Native("dism.exe", "/Online", "/Cleanup-Image",
                    action == MaintenanceActionId.ScanWindowsImage ? "/ScanHealth" : "/RestoreHealth",
                    "/English", "/NoRestart", "/LogPath:" + servicingLog);
                break;
            case MaintenanceActionId.VerifySystemFiles:
            case MaintenanceActionId.RepairSystemFiles:
                start = Native("sfc.exe", action == MaintenanceActionId.VerifySystemFiles ? "/verifyonly" : "/scannow");
                // SFC writes UTF-16 when stdout is redirected.
                start.StandardOutputEncoding = Encoding.Unicode;
                break;
            case MaintenanceActionId.AnalyzeSystemDrive:
                start = TrustedPowerShell.Create(WrapPowerShell(
                    "$drive = [System.IO.Path]::GetPathRoot([System.Environment]::SystemDirectory).Substring(0,1); " +
                    "Storage\\Optimize-Volume -DriveLetter $drive -Analyze -Verbose -ErrorAction Stop"),
                    WindowsPowerShellModule.Utility, WindowsPowerShellModule.Storage);
                break;
            default:
                throw new ArgumentOutOfRangeException(nameof(action));
        }

        // Never terminate a Windows repair because a timer expired.
        var result = await RunAsync(sessionId, logName, start,
            repair ? Timeout.InfiniteTimeSpan : TimeSpan.FromMinutes(45));
        if (result.LogError is not null)
            return new MaintenanceStepResult(action, StepOutcome.Failed,
                $"O comando terminou com código {result.ExitCode}, mas o registro do log falhou: {result.LogError}. O reparo não foi interrompido; verifique também os registros do Windows.", result.LogFile);
        if (result.TimedOut)
            return new MaintenanceStepResult(action, StepOutcome.Failed,
                "O limite de espera do diagnóstico foi excedido. A supervisão terminou; uma verificação do Defender já iniciada pode continuar no Windows.", result.LogFile);
        if (result.ExitCode is not 0 and not 3010)
            return new MaintenanceStepResult(action, StepOutcome.Failed,
                $"O comando retornou código {result.ExitCode}. Consulte o log para o diagnóstico; não foi confirmada correção.", result.LogFile);

        var message = action switch
        {
            MaintenanceActionId.DefenderQuickScan => "O comando de verificação rápida do Defender terminou. Consulte Segurança do Windows para resultados, ameaças e ações necessárias.",
            MaintenanceActionId.ScanWindowsImage => "DISM concluiu a análise. Consulte o log para saber se encontrou corrupção; o diagnóstico não corrige a imagem.",
            MaintenanceActionId.RepairWindowsImage => "DISM concluiu o comando de reparo. Consulte os logs e valide o problema original; este resultado não garante que todos os erros foram corrigidos.",
            MaintenanceActionId.VerifySystemFiles => "SFC concluiu a verificação. Código zero não garante ausência de corrupção; consulte a saída e o registro CBS do Windows.",
            MaintenanceActionId.RepairSystemFiles => "SFC concluiu o comando de reparo. Código zero não confirma que todos os arquivos foram corrigidos; consulte a saída e o registro CBS do Windows.",
            MaintenanceActionId.AnalyzeSystemDrive => "A análise do volume terminou. Consulte o log; nenhuma otimização ou desfragmentação foi solicitada.",
            _ => throw new ArgumentOutOfRangeException(nameof(action))
        };
        if (result.ExitCode == 3010) message += " O Windows solicitou reinicialização; reinicie quando for conveniente.";
        return new MaintenanceStepResult(action, StepOutcome.Succeeded, message, result.LogFile);
    }

    private static string WrapPowerShell(string body) =>
        "& { $ErrorActionPreference = 'Stop'; try { " + body +
        "; exit 0 } catch { Microsoft.PowerShell.Utility\\Write-Error $_ -ErrorAction Continue; exit 1 } }";

    private static ProcessStartInfo Native(string executable, params string[] arguments)
    {
        var start = new ProcessStartInfo(Path.Combine(Environment.SystemDirectory, executable))
        {
            UseShellExecute = false, CreateNoWindow = true,
            RedirectStandardOutput = true, RedirectStandardError = true,
            WorkingDirectory = Environment.SystemDirectory
        };
        foreach (var argument in arguments) start.ArgumentList.Add(argument);
        return start;
    }

    private static async Task<CommandResult> RunAsync(Guid sessionId, string logName, ProcessStartInfo start, TimeSpan timeout)
    {
        var logPath = Path.Combine(SessionStore.GetSessionDirectory(sessionId), logName);
        var logStream = SessionStore.CreateLog(sessionId, logName);
        var writer = new StreamWriter(logStream, new UTF8Encoding(false), leaveOpen: true) { AutoFlush = true };
        var logState = new LogState();
        try
        {
            // Logging must work before a command starts. After launch, drain both pipes even if disk writes fail.
            await writer.WriteLineAsync($"ZEUS — {DateTimeOffset.UtcNow:O}");
            await writer.WriteLineAsync($"Executável: {start.FileName}");
            using var process = Process.Start(start) ?? throw new InvalidOperationException("O comando não iniciou.");
            using var writeLock = new SemaphoreSlim(1, 1);
            var stdout = PumpAsync(process.StandardOutput, writer, writeLock, logState, "OUT");
            var stderr = PumpAsync(process.StandardError, writer, writeLock, logState, "ERR");
            var timedOut = false;
            try
            {
                if (timeout == Timeout.InfiniteTimeSpan) await process.WaitForExitAsync();
                else await process.WaitForExitAsync().WaitAsync(timeout);
            }
            catch (TimeoutException)
            {
                timedOut = true;
                if (!process.HasExited) process.Kill(entireProcessTree: true);
                await process.WaitForExitAsync();
            }
            var output = await stdout;
            await stderr;
            await WriteLogAsync(writer, writeLock, logState,
                $"Fim: {DateTimeOffset.UtcNow:O}; código: {process.ExitCode}; timeout: {timedOut}");
            try { await writer.DisposeAsync(); }
            catch (Exception exception) { logState.Record(exception); }
            try { await logStream.DisposeAsync(); }
            catch (Exception exception) { logState.Record(exception); }
            return new CommandResult(process.ExitCode, output, timedOut, logPath, logState.Error);
        }
        finally
        {
            // Disposal must not hide the original failure or terminate a still-running repair.
            try { await writer.DisposeAsync(); } catch { }
            try { await logStream.DisposeAsync(); } catch { }
        }
    }

    private static async Task<string> PumpAsync(StreamReader reader, StreamWriter writer, SemaphoreSlim writeLock,
        LogState logState, string channel)
    {
        var preview = new StringBuilder();
        while (await reader.ReadLineAsync() is { } line)
        {
            if (preview.Length < 16 * 1024) preview.AppendLine(line[..Math.Min(line.Length, 16 * 1024 - preview.Length)]);
            await WriteLogAsync(writer, writeLock, logState, $"[{channel}] {line}");
        }
        return preview.ToString();
    }

    private static async Task WriteLogAsync(StreamWriter writer, SemaphoreSlim writeLock, LogState logState, string line)
    {
        await writeLock.WaitAsync();
        try
        {
            if (logState.Error is not null) return;
            try { await writer.WriteLineAsync(line); }
            catch (Exception exception) { logState.Record(exception); }
        }
        finally { writeLock.Release(); }
    }

    private sealed class LogState
    {
        private string? _error;
        public string? Error => Volatile.Read(ref _error);
        public void Record(Exception exception) => Interlocked.CompareExchange(ref _error, exception.Message, null);
    }
}
